project:
  type: website

website:
  title: "Biomath 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: pulse
      dark: vapor
    css: styles.css
    toc: true


