project:
  type: website

website:
  title: "Biomath 2024"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: links.qmd
        text: Links

format:
  html:
    theme: 
      light: pulse
      dark: vapor
    css: styles.css
    toc: true


