---
title: "Basic Biomathematical Work Flow and Modeling"
bibliography: "bibliography.bib"
---

## Basic Biomathematical Work Flow

1) Start with some real world phenomenon of interest from the life sciences.

2) By making some set of simplifying assumptions, abstract from the real world in order to highlight essential features for the purposes of answering some specific question or solving some particular problem. 

3) Represent your abstraction from step 2 as a **mathematical model**.

4) Use techniques from applied mathematics or scientific computing in order to understand the mathematical representation in step 3 with the goal of solving a problem or answering a question. 

5) Place your results from step 4 in the context of the original real world biological phenomenon.

## An Example

[Inflammation](https://en.wikipedia.org/wiki/Inflammation#:~:text=Inflammation%20(from%20Latin%3A%20inflammatio),blood%20vessels%2C%20and%20molecular%20mediators.) is a normal part of the [immune response](https://en.wikipedia.org/wiki/Immune_response) for defense against invasion by foreign cells or molecules. However, inflammation may become chronic and lead to disease, [sepsis](https://en.wikipedia.org/wiki/Sepsis), and even death. For the purposes of both treatment and prevention of disease, it is important to understand the conditions that lead to chronic inflammation. 

Without going into the biological and chemical details, we know that inflammation is controlled and mediated by immune cells ([the macrophage](https://en.wikipedia.org/wiki/Macrophage)) whose behavior is regulated by signaling molecules known as [cytokines](https://en.wikipedia.org/wiki/Cytokine). Thus, it is reasonable for the purposes of abstraction to encapsulate the immune response by the activities of macrophage cells, cytokines, and an invading body such as a bacteria cell. This is exactly what is done in the paper [@heraldGeneralModelInflammation2010]. 

Figure 2 shows a schematic corresponding to our abstraction of the immune response. The macrophage cell population responds to bacterial invasion and produces cytokines that mediate the immune response. The exact details of the interactions are governed by model parameters and mathematical relationships between the interacting cell populations and cytokines. 

![Schematic of inflammation model. This corresponds roughly to Figure 1 in [@heraldGeneralModelInflammation2010].](https://github.com/jmgraham30/TopicsInBiomath/blob/master/Figures/inflammationDiagram.png?raw=true){#fig-fig2}


In [@heraldGeneralModelInflammation2010], the author converts the model diagram into a mathematical model in the form of a coupled system of nonlinear differential equations shown here:

\begin{align}
\frac{dM}{dt} &= s + \frac{r C}{1 + k_{1} C} - m_{d} M, \\
\frac{dC}{dt} &=  p_{c} B M + M \frac{a C}{(1 + k_{2} C)}\frac{1}{(1 + k_{3} A)} - c_{d} C,\\
\frac{dA}{dt} &=  p_{a} C M - a_{d} A, \\ 
\frac{dB}{dt} &= g B - b_{d} M B.
\end{align}

Later on in the course we will study this model in more detail. For now, note that

* $M$ - macrophage cell population
* $C$ - inflammatory cytokine concentration 
* $A$ - anti-inflammatory cytokine concentration
* $B$ - bacteria cell population 


In the paper, the author uses the model equations to show that under a certain set of circumstances a bacterial pathogen will not provide a sufficient trigger to cause chronic inflammation. On the other hand, if conditions are right, even a minor bacterial infection can lead to chronic inflammation. We leave the details of the analysis for later in the course. Notice that this example contains all of the components of the basic biomathematics work flow. 

1) The real world phenomenon of interest from the life sciences is inflammation.
2) Figure 2 corresponds to an abstraction of the biochemical details of the immune system highlighting what is thought to be the essential features of the inflammatory response. 
3) Clearly there is a mathematical model. A major portion of this course is devoted to understanding how one might come up with such a system of equations. These were not simply pulled out of thin air. 
4) In [@heraldGeneralModelInflammation2010], the author uses techniques from [dynamical systems](https://en.wikipedia.org/wiki/Dynamical_systems_theory) and [bifurcation theory](https://en.wikipedia.org/wiki/Bifurcation_theory) in order to derive useful information from the model equations. 
5) The author's analysis of the model system explains some aspects of inflammation and pinpoints conditions that lead to chronic inflammation. The authors work also explains why certain therapies for chronic inflammation are not successful. 

There are still many questions about inflammation to be addressed beyond what is done in [@heraldGeneralModelInflammation2010]. However, in order to make progress more details of the immune response may need to be included. This will involve either modifying the system of equations displayed in this section, or using a different mathematical model altogether. For now, the point to take away is that, often times, this is how work in biomathematics proceeds. In the next lecture, we will start to learn some essential principles of mathematical modeling that will help us to see where equations such as the ones presented in this section come from. 



## Modeling

### What is a Mathematical Model? 

Before we begin to address the question of what is a mathematical model, let's spend some time focusing just on not-necessarily-mathematical models. Work in science and engineering often proceeds by employing models. What is a model? Consider the following quotation:

> A model is a rendition of a reality which is often too difficult or impossible to handle directly. A model is always a simplification, and a good model is one that captures the essential features of reality, leaving the unessential out [@calvettiComputationalMathematicalModeling2013]. 

A great example of a scientific model is the [Bohr model](https://en.wikipedia.org/wiki/Bohr_model) for the atom. This model posits that an atom is made up of a small dense nucleus surrounded by orbiting electrons. This is a model because it does not include many atomic and nuclear details. It is a useful model because it leads to an explanation of certain chemical properties of atoms that could not be derived prior to the use of the Bohr model. Many biologists use [model organisms](https://en.wikipedia.org/wiki/Model_organism) to investigate the biological world. For example, people interested in understanding the evolution of social behavior study specific species of ants or bees. These insects are used because they are relatively easy to keep in a lab or to observe in nature and are also easy to manipulate experimentally. The use of [animal models](https://en.wikipedia.org/wiki/Animal_disease_model) is also widespread in the study of disease and drug therapies.  

A mathematical model plays a similar role to models in the more general sense that we just described, but as you might imagine mathematical models are formulated and implemented mathematically. In the last lecture, we very briefly indicated two mathematical models. One for the growth of a population and another for certain cellular and molecular interactions that occur during inflammation. Let's look at another example of a mathematical model, this time one coming from physics that is likely familiar to you from a course in ordinary differential equations. 

Physics and mechanics in particular is often interested in the motion of a point particle. (Notice that point particles are an abstraction from reality.) Newton's laws tell us, among other things, that the sum of all forces acting on a mass is proportional to the acceleration of the object. Furthermore, the constant of proportionality is the mass. In notation, we have that $F=ma$. Now, while $F=ma$ is an equation and you could reasonably argue that it is a "mathematical model" for how the physical world works, $F=ma$ is not really representative of what we mean by a mathematical model in most instances. The reason is that it is a general statement, a theory and not a reference to something specific. However, we can use $F=ma$ to construct mathematical models in more specific situations.      

Suppose for example that we are concerned with the motion of a particle of mass $m$ attached to a spring. We can model the total force that is applied to the mass by the spring via the equation $F=-kx$. This says that the force due to the spring is linearly proportional to the displacement of the mass from it's equilibrium (resting) position. (Again, this is an abstraction from reality.) The constant of proportionality $k$ is called the spring constant. It encodes physical properties of a spring such as its stiffness. Taken together with $F=ma$ and using that acceleration is the second derivative of displacement we arrive at a **mathematical model**

$\frac{d^2 x}{dt^2} = -\frac{k}{m}x.$

This is a model because it is based on several abstractions from reality and ignores some details such as more fine-grained details about the material properties of real world springs. It also assumes an ideal situation where there is no friction. 

As you have seen in a differential equations course, or by using methods we will discuss later, it can be deduced based on the form of the equation $\frac{d^2 x}{dt^2} = -\frac{k}{m}x$ that such a mass will oscillate with a fixed period and frequency determined by the values for $k$ and $m$. This leads us to another important point. There are several levels of "variable" involved in the model $\frac{d^2 x}{dt^2} = -\frac{k}{m}x$. There is the independent variable $t$ for time, the dependent variable for the unknown displacement $x$ (the quantity we are ultimately most interested in), and there are the **parameters** $k$ and $m$. 

We will see that most mathematical models involve parameters and it will become very important to understand how the values of parameters influence the results obtained from the model. Also very important is to note that variables and parameters correspond to quantities and thus have some set of units associated with them. We will spend a lot of time talking about why units of measurement are important but take note now that a mathematical model can not make sense if there is an inconsistency between units for parameters or variables. 

The last example provides some insight into mathematical modeling, that is, the process of constructing or deriving a model. We begin with an abstraction from reality that represents those parts of the world in which we are most interested in, then we specify quantities that we want to relate, establish mathematical notation, and finally write down an equation that becomes our mathematical model. While our last example was very simple (too simple), it still serves to highlight the modeling process. The next section elaborates on this.


### Mathematical Modeling 

It is important to realize two facts about mathematical modeling, especially in the context of biomathematics, from the start:

1) Mathematical modeling is as much art as it is science. The point is that mathematical modeling is not routine or algorithmic. Successful modeling requires creativity and intuition developed through experience. 

2) Mathematical modeling will almost certainly involve repeated refinements. Unless there is a very strong reason to do otherwise, it's best to start with the simplest possible reasonable model, even at the risk of oversimplification. If the model produces incorrect or inaccurate results relative to the problem of interest, then the model can be revised in order to fix what is glaringly wrong. 

In the next lecture, we will begin to address specific techniques that can help one to get started with mathematical modeling. Here we will provide a conceptual outline of the modeling process in the form of a series of steps that one typically carries out during the course of the modeling process.

1) Formulate the question or state your problem. Explicitly write down assumptions and what is known about the system that you want to develop a model for. 

2) Identify key quantities and define variables and parameters of interest. At this stage you should take careful note of the units of measurement that are associated with all of the model variables and parameters.

3) Develop a qualitative description of your model. Use diagrams or word equations to describe the relationships between variables. In the next lecture we will discuss compartment modeling which is a commonly used method for organizing the processes and interactions of variables in a way that helps one to more easily write down model equations. 
4) Write down model equations corresponding to the qualitative description in the previous step. Perform [dimensional analysis](https://en.wikipedia.org/wiki/Dimensional_analysis) (covered in detail later) to make sure that there are no inconsistencies in your equations regarding units. At this stage it is very helpful to construct a table that lists all of the variables and parameters appearing in the model. The table should include the units of measurement for all of the variables and parameters as well as any specific parameters values that are known from experiment or the existing literature. 

5) [Nondimensionalize](https://en.wikipedia.org/wiki/Nondimensionalization) the model. Later we will cover nondimensionalization in detail. This is a process founded on the [Buckinghma $\pi$ theorem](https://en.wikipedia.org/wiki/Buckingham_%CF%80_theorem) in which variables and parameters are rescaled to remove units. This process is extremely important as it often simplifies the model by reducing the number of parameters and pinpoints the most significant parameters (or parameter combinations) in the model.

At this stage you will be ready to analyze or implement your model in order to obtain results such as qualitative or quantitative predictions. The next thing to do is determine if the model results are consistent with known information or experimental results. You have to do something to decide if your model is successful or should be revised in order to address your starting question or solve the problem you have posed. 

With this overview in hand, the next lecture will cover compartment modeling and we will start to see concrete examples of mathematical models and the modeling process. 

